core/urls.py
from django.urls import path

from . import views

app_name = 'core'

urlpatterns = [
    # homepage
    path('', views.HomeView.as_view(), name='home'),

    # product
    path('product/<slug>/', views.ProductDetailView.as_view(), name='product'),

    # cart
    path('add-to-cart/<slug>/', views.add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<slug>/',
         views.remove_from_cart, name='remove-from-cart'),

    # checkout
    path('checkout/', views.checkout, name='checkout'),
]

djecommerce/urls.py
from django.contrib import admin
from django.urls import (include, path)
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls', namespace='core')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

products/urls.py
from django.urls import path
from . import views

urlpatterns = [
   path('', views.index, name='products'),
]

core/models.py
from django.conf import settings
from django.db import models
from django.shortcuts import reverse


# product category choices
CATEGORY_CHOICES = (
    ('S', 'Shirt'),
    ('SW', 'Sport wear'),
    ('OW', 'Outwear'),
)
# product label choices
LABEL_CHOICES = (
    ('P', 'primary'),
    ('S', 'secondary'),
    ('D', 'dark'),
)


# Item -> (product)
class Item(models.Model):
    title = models.CharField(max_length=100)
    price = models.FloatField()
    discount_price = models.FloatField(null=True, blank=True)
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=2)
    label = models.CharField(choices=LABEL_CHOICES, max_length=1)
    slug = models.SlugField()
    description = models.TextField(max_length=255)

    def __str__(self):
        return self.title

    # product url
    def get_absolute_url(self):
        return reverse("core:product", kwargs={"slug": self.slug})

    # add to cart url
    def get_add_to_cart_url(self):
        return reverse("core:add-to-cart", kwargs={"slug": self.slug})

    # remove from cart url
    def get_remove_from_cart_url(self):
        return reverse("core:remove-from-cart", kwargs={"slug": self.slug})

    # product discount(%)
    def get_discounted(self):
        # change those float variables to integers
        discounted_price = int(self.discount_price)
        original_price = int(self.price)
        # get the discount
        if original_price > discounted_price and discounted_price >= 1:
            discount = ((discounted_price / original_price) * 100)
            msg = round(discount)
            result = f"{msg}% OFF"
        else:
            result = None
        # return percentage
        return result

    # price validation
    def prices_are_ok(self):
        discounted_price = int(self.discount_price)
        original_price = int(self.price)
        if discounted_price >= 1 and original_price > discounted_price:
            return True
        else:
            return False


# Order Item -> (cart)
class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    ordered = models.BooleanField(default=False)

    def __str__(self):
        return f"{ self.item.title } - X{ self.quantity }"


# Order -> (order)
class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

products/models.py
from django.db import models


# Product
class Product(models.Model):
    name = models.CharField(max_length=250)
    price = models.FloatField()
    stock = models.IntegerField()
    image_url = models.CharField(max_length=2083)

    def __str__(self):
        return self.name


# Offer
class Offer(models.Model):
    code = models.CharField(max_length=7)
    description = models.CharField(max_length=225)
    discount = models.FloatField()

    def __str__(self):
        return self.code

core/views.py
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.shortcuts import (get_object_or_404, redirect, render)
from django.utils import timezone
from django.views.generic import (ListView, DetailView)

from .models import (Item, OrderItem, Order)


# home
class HomeView(ListView):
    model = Item
    paginate_by = 8
    template_name = 'home/index.html'


# product
class ProductDetailView(DetailView):
    model = Item
    template_name = 'product/product-page.html'


# add to cart
@login_required
def add_to_cart(request, slug):
    # get the specified item
    item = get_object_or_404(Item, slug=slug)
    # get or create an Order Item and add the item to list
    order_item, created = OrderItem.objects.get_or_create(
        item=item, user=request.user, ordered=False)
    # query existing unfulfilled orders of the current user
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    # (if any) -> increase its quantity
    if order_qs.exists():
        # grab the Order queryset
        order = order_qs[0]
        # check if the order_item is in this existing order
        if order.items.filter(item__slug=item.slug).exists():
            # increment the order_item's quantity in the Order(cart)
            order_item.quantity += 1
            # save the order_item to (cart)
            order_item.save()
            # inform the user of the action done
            messages.info(request, "This item's quantity has been updated!",
                          fail_silently=False)
        # if the order_item is not in this existing order, add it
        else:
            # inform the user of the action done
            messages.success(
                request, "This item has been added to your cart!", fail_silently=False)
            order.items.add(order_item)
    # (if none) -> create it
    else:
        ordered_date = timezone.now()
        order = Order.objects.create(
            user=request.user, ordered_date=ordered_date)
        # add the order_item to the new Order
        order.items.add(order_item)
    # now back to the item's page
    return redirect('core:product', slug=slug)


# remove from cart
@login_required
def remove_from_cart(request, slug):
    item = get_object_or_404(Item, slug=slug)
    # query existing unfulfilled orders from the current user
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    # (if any) -> remove it from cart
    if order_qs.exists():
        # grab the Order queryset
        order = order_qs[0]
        # check if the item is among the grabbed order's items
        if order.items.filter(item__slug=item.slug).exists():
            # query the current item inside the current OrderItem(cart)
            order_item = OrderItem.objects.filter(
                item=item, user=request.user, ordered=False)[0]
            # remove that item from the OrderItem(s)
            order.items.remove(order_item)
            # inform the user of the action done
            messages.warning(request, "This item was removed from your cart!",
                             fail_silently=False)
        else:
            # inform the user of the action done
            messages.error(
                request, "This item was not in your cart!", fail_silently=False)
            return redirect('core:product', slug=slug)
    # (if none) -> stay on the item's page
    else:
        # inform the user of the action done
        messages.error(request, "Sorry! You don't have an active order!",
                       fail_silently=False)
        return redirect('core:product', slug=slug)
    # now back to the item's page
    return redirect('core:product', slug=slug)


# checkout
@login_required
def checkout(request):
    return render(request, 'checkout/checkout-page.html')

products/views.py
from django.shortcuts import render
from .models import (Product)


# /products -> index
def index(request):
    products = Product.objects.all()
    context = {'products': products}
    return render(request, 'products.html', context)

products/templates/base/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>PyShop | {% block title %}{% endblock %}</title>
</head>
<body>
{% block content %}
{% endblock %}
</body>
</html>

products/templates/products.html
{% extends 'base/base.html' %}
{% block title %}Products{% endblock %}
{% block content %}
  <h1>PRODUCTS</h1>
  <ul>
    {% for product in products %}
      <li>{{ product.name }} (${{ product.price }})</li>
    {% endfor %}
  </ul>
{% endblock %}

templates/base.html
<!DOCTYPE html>{% load static %}
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <meta name="author" content="Elvis Kemboi">
  <meta name="description" content="This is a Django-powered e-commerce website.">
  <meta name="keywords" content="Django, commerce, e-commerce, store, online, cool, iamelviskemboi, Elvis">
  <!-- Title -->
  <title>PyShop | {% block head_title %}{% endblock %}</title>
  {% block extra_head %}
  {% endblock %}
  <!-- mdb styles -->
  <link rel="stylesheet" href="{% static 'mdb/css/bootstrap.css' %}">
  <link rel="stylesheet" href="{% static 'mdb/css/style.min.css' %}">
  <link rel="stylesheet" href="{% static 'mdb/css/mdb.min.css' %}">
  <!-- master style -->
  <link rel="stylesheet" href="{% static 'master/css/master/master.css' %}">
  <!-- extra styles -->
  {% block styles %}{% endblock %}
</head>
<!-- Navbar -->
<nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
  <div class="container">

    <!-- Brand -->
    <a class="navbar-brand waves-effect" href="{% url 'core:home' %}">
      <strong class="clr-green">PyShop</strong>
    </a>

    <!-- Collapse -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <!-- Links -->
    <div class="collapse navbar-collapse" id="navbarSupportedContent">

      <!-- Left -->
      <ul class="navbar-nav mr-auto">
        <!-- 
        <li class="nav-item active">
          <a class="nav-link waves-effect" href="{% url 'core:home' %}">Home
            <span class="sr-only">(current)</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link waves-effect" href="{% url 'core:checkout' %}">Checkout</a>
        </li>
       -->
      </ul>

      <!-- Right -->
      <ul class="navbar-nav nav-flex-icons">
        {% if request.user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link waves-effect" href="{% url 'core:checkout' %}">
            <span class="badge red z-depth-1 mr-1"></span>
            <i class="clr-green fas fa-shopping-cart"></i>
            <span class="clearfix d-none d-sm-inline-block"> Cart </span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link waves-effect" href="{% url 'account_logout' %}">
            <span class="badge red z-depth-1 mr-1"></span>
            <i class="clr-green fas fa-power-off fa-1x"></i>
            <span class="clearfix d-none d-sm-inline-block"> </span>
          </a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link waves-effect" href="{% url 'account_login' %}">
            <span class="badge red z-depth-1 mr-1"></span>
            <i class="clr-green fas fa-sign-in-alt fa-1x"></i>
            <span class="clearfix d-none d-sm-inline-block">Login</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link waves-effect" href="{% url 'account_signup' %}">
            <span class="badge red z-depth-1 mr-1"></span>
            <i class="clr-green fas fa-user-plus fa-1x"></i>
            <span class="clearfix d-none d-sm-inline-block">Signup</span>
          </a>
        </li>
        {% endif %}
      </ul>

    </div>

  </div>
</nav>
<!-- Navbar -->

<!-- Alerts -->
{% if messages %}
{% include 'messages/messages.html' %}
{% endif %}
<!-- Alerts -->

<!-- Main Content -->
{% block content %}
{% endblock %}

{% block extra_body %}
{% endblock %}
<!-- Main Content -->

<!--Footer-->
<div class="spc-up">
  <footer class="page-footer text-center font-small mt-4 wow fadeIn footr">
    <hr class="my-4">
    <!-- Social icons -->
    <div class="pb-4 pt-3">
      <a href="{% url 'core:home' %}">
        <i class="fab fa-facebook-f ml-3 mr-3 icon"></i>
      </a>

      <a href="{% url 'core:home' %}">
        <i class="fab fa-twitter mr-3 icon"></i>
      </a>

      <a href="{% url 'core:home' %}">
        <i class="fab fa-youtube mr-3 icon"></i>
      </a>

      <a href="{% url 'core:home' %}">
        <i class="fab fa-github mr-3 icon"></i>
      </a>

      <a href="{% url 'core:home' %}">
        <i class="fab fa-codepen mr-3 icon"></i>
      </a>
    </div>
    <!-- Social icons -->

    <!--Copyright-->
    <div class="footer-copyright py-3 pt-3">
      <i class="fas fa-copyright"></i> 2020 Copyright<a href="{% url 'core:home' %}"> PyShop </a>
    </div>
    <!--/.Copyright-->

  </footer>
</div>
<!--/.Footer-->
<!-- mdb scripts -->
<script src="{% static 'mdb/js/jquery-3.4.1.min.js' %}"></script>
<script src="{% static 'mdb/js/bootstrap.min.js' %}"></script>
<script src="{% static 'mdb/js/popper.min.js' %}"></script>
<script src="{% static 'mdb/js/mdb.min.js' %}"></script>
<!-- Font Awesome -->
<script src="{% static 'master/js/fontawesome/all.js' %}"></script>
<!-- master script -->
<script src="{% static 'master/js/master/main.js' %}"></script>
<!-- extra scripts -->
{% block scripts %}{% endblock %}

</html>

templates/home/index.html
{% extends 'base.html' %}{% load static %}
{% block head_title %}home{% endblock head_title %}
{% block styles %}
<style type="text/css">
  html,
  body,
  header,
  .carousel {
    height: 60vh;
  }

  @media (max-width: 740px) {

    html,
    body,
    header,
    .carousel {
      height: 100vh;
    }
  }

  @media (min-width: 800px) and (max-width: 850px) {

    html,
    body,
    header,
    .carousel {
      height: 100vh;
    }
  }
</style>
{% endblock %}
{% block content %}

<body class="bg-white">
  <!--Main layout-->
  <main>
    <div class="container">
      {% if not messages %}
      <div class="mt-5 pt-4">
        {% endif %}
        <!--Navbar-->
        <nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-3 mb-5">

          <!-- Navbar brand -->
          <span class="navbar-brand">Categories:</span>

          <!-- Collapse button -->
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
            aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <!-- Collapsible content -->
          <div class="collapse navbar-collapse" id="basicExampleNav">

            <!-- Links -->
            <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
                <a class="nav-link" href="#">All
                  <span class="sr-only">(current)</span>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Shirts</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Sport wears</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Outwears</a>
              </li>

            </ul>
            <!-- Links -->

            <form class="form-inline">
              <div class="md-form my-0">
                <input class="form-control mr-sm-2" type="text" placeholder="@{{ request.user.username }}"
                  aria-label="Search">
              </div>
            </form>
          </div>
          <!-- Collapsible content -->

        </nav>
        <!--/.Navbar-->

        <!--Section: Products v.3-->
        <section class="text-center mb-4">
          <!--Grid row-->
          <div class="row wow fadeIn">
            {% for product in page_obj %}
            <!--Grid column-->
            <div class="col-lg-3 col-md-6 mb-4">

              <!--Card-->
              <div class="card">

                <!--Card image-->
                <div class="view overlay">
                  <img src="{% static 'mdb/img/products/1.png' %}" class="card-img-top" alt="">
                  <a href="{{ product.get_absolute_url }}">
                    <div class="mask rgba-white-slight"></div>
                  </a>
                </div>
                <!--Card image-->

                <!--Card content-->
                <div class="card-body text-center">
                  <!--Category & Title-->
                  <a href="" class="grey-text">
                    <h5>{{ product.get_category_display }}</h5>
                  </a>
                  <h5>
                    <strong>
                      <a href="{{ product.get_absolute_url }}" class="dark-grey-text">{{ product.title }}
                        <span class="badge badge-pill bg-{{ product.get_label_display }}">NEW</span>
                      </a>
                    </strong>
                  </h5>

                  <h4 class="font-weight-bold green-text">
                    {% if product.discount_price %}
                    <strong>${{ product.discount_price }}</strong>
                    {% else %}
                    <strong>${{ product.price }}</strong>
                    {% endif %}
                  </h4>

                </div>
                <!--Card content-->

              </div>
              <!--Card-->

            </div>
            <!--Grid column-->

            {% endfor %}
          </div>
          <!--Grid row-->
        </section>
        <!--Section: Products v.3-->

        <hr>

        <!--Pagination-->
        {% if is_paginated %}
        <nav class="d-flex justify-content-center wow fadeIn">
          <ul class="pagination pg-green">
            {% if page_obj.has_previous %}
            <li class="page-item">
              <!-- <a class="page-link" href="?page=1">&laquo;</a> -->
              <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                <span aria-hidden="true" style="color: #205823 !important;">&laquo;</span>
                <span class="sr-only">Previous</span>
              </a>
            </li>
            {% endif %}

            <li class="page-item active">
              <a class="page-link" href="?page={{ page_obj.number }}">{{ page_obj.number }}</a>
              <span class="sr-only">(current)</span>
            </li>

            {% if page_obj.has_next %}
            <li class="page-item">
              <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                <span aria-hidden="true" style="color: #205823 !important;">&raquo;</span>
                <span class="sr-only">Next</span>
              </a>
              <!-- <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">&raquo;</a> -->
            </li>
            {% endif %}
          </ul>
        </nav>
        <div class="float-right">
          <code class="current pagy">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
          </code>
        </div>
        {% endif %}
        <!--Pagination-->

      </div>
    </div>
  </main>
  <!--Main layout-->
  {% endblock %}
  {% block scripts %}
  <!-- Initializations -->
  <script type="text/javascript">
    // Animations initialization
    new WOW().init();
  </script>
</body>
{% endblock %}

templates/messages/messages.html
<div class="container mt-5 pt-4">
  <div class="text-center msg">
    {% for message in messages %}
    <div class="alert alat-{{ message.tags }} alert-{{ message.tags }} alert-dismissable fade show" role="alert">
      <span class="text-3 font font-weight-normal">{{ message }}</span>
      <button class="close" type="button" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">
          <i class="fa fa-times"></i>
        </span>
      </button>
    </div>
    {% endfor %}
  </div>
</div>

templates/product/product-page.html
{% extends 'base.html' %}{% load static %}
{% block head_title %}Product{% endblock head_title %}
{% block content %}

<body class="bg-white">
  <!--Main layout-->
  {% if not messages %}
  <main class="mt-5 pt-4">
    {% endif %}
    <div class="container dark-grey-text mt-5">
      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <img src="{% static 'mdb/img/products/1.png' %}" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-6 mb-4">
          <!--Content-->
          <div class="p-4">
            <div class="mb-3">
              <h1 class="font-weight-light">{{ object.title }}</h1>
              <a href="">
                <span class="badge text-light bg-{{ object.get_label_display }} mr-1">
                  {{ object.get_category_display }}
                </span>
                {% if object.get_discounted is not 0 and object.get_discounted is not None %}
                <span class="badge bg-orange text-white mr-1">{{ object.get_discounted }}</span>
                {% endif %}
              </a>

            </div>

            <p class="lead">
              <span class="mr-1">
                {% if object.discount_price and object.prices_are_ok %}
                <span class="del text-3">${{ object.price }}</span>
                <span class="text-2" style="color:darkgreen !important;">${{ object.discount_price }}</span>
                {% else %}
                <span class="text-2" style="color:darkgreen !important;">${{ object.price }}</span>
                {% endif %}
              </span>
            </p>

            <p class="lead font-weight-bold">Description</p>
            <p>{{ object.description }}</p>
            {% comment '' %}
            <form class="d-flex justify-content-left">
              <!-- Default input -->
              <input type="number" value="1" aria-label="Search" class="form-control" style="width: 100px">
              <button class="btn btn-success btn-md my-0 p" type="submit">Add to cart
                <i class="fas fa-shopping-cart ml-1"></i>
              </button>
              {% endcomment %}
              <a class="btn btn-primary btn-md my-0 p" href="{{ object.get_add_to_cart_url }}">
                Add to cart
                <i class="fas fa-shopping-cart ml-1"></i>
              </a>
<!-- 
              <a class="btn btn-danger btn-md my-0 p" href="{{ object.get_remove_from_cart_url }}">
                Remove from cart
                <i class="fas fa-times ml-1"></i>
              </a>
 -->
            </form>

          </div>
          <!--Content-->

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <hr>

      <!--Grid row-->
      <div class="row d-flex justify-content-center wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 text-center">

          <h4 class="my-4 h4">Additional information</h4>

          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus suscipit modi sapiente illo soluta odit
            voluptates,
            quibusdam officia. Neque quibusdam quas a quis porro? Molestias illo neque eum in laborum.</p>

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-lg-4 col-md-12 mb-4">

          <img src="{% static 'mdb/img/products/1.png' %}" class="product-dp img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-4 col-md-6 mb-4">

          <img src="{% static 'mdb/img/products/1.png' %}" class="product-dp img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-4 col-md-6 mb-4">

          <img src="{% static 'mdb/img/products/1.png' %}" class="product-dp img-fluid" alt="">

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

    </div>
  </main>
  <!--Main layout-->
</body>
{% endblock content %}